# If issues appear when trying to load zarr, cfgrib, try 'pip install xarray[complete]'
name: shift_env
channels:
    - conda-forge
    - defaults
dependencies:
- python>=3.8 # pin version for conda
- anaconda
- pip
- mamba
- proj
- pyproj
- pystac-client
- hvplot
- geoviews
- geopandas
- fiona
- cartopy
- rioxarray
- s3fs
- pooch
- xarray
- shapely
- earthpy
- zarr
- shapely
- pandas
- h5py
- matplotlib
- numpy
- dask
- rasterio
- holoviews
- pyresample
- pip:
    - pathlib
    - GDAL
    - boto3
    - s3fs
